welcome: "Привіт! Тут ти можеш запропонувати контент для нашого каналу. "
templates:
  - title: "Запропонувати"
    description: "Тут ти можеш запропонувати контент для каналу."
    toend: "Ми обовʼязково побачимо те, що ви запропонували."
    complete: "Дякуємо за Ваш вклад! Якщо контент буде прийнято, ти побачиш його на каналі."
    entries:
    - mode: "file"
      title: "Ваше медіа (картинка, відео, анімація)"
      incorrect: "Неправильний тип файлу."
      description: "Завантажте свій файл."
  
